framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - validation
            query.bus: ~
            event.bus: ~

        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        routing:
            App\Domain\Shared\Bus\Query: sync
            App\Domain\Shared\Bus\Command: async
            App\Domain\Shared\Event\DomainEvent: async
