services:
  nginx:
    container_name: 'nginx'
    image: nginx:1.30-alpine
    restart: unless-stopped
    volumes:
      - '.:/var/www/html:ro'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
    ports:
      - '80:80'
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - app_network

  php-fpm:
    container_name: 'php-fpm'
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      target: dev
    volumes:
      - '.:/var/www/html'
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm -t || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app_network

  worker:
    container_name: worker
    restart: unless-stopped
    depends_on:
      php-fpm:
        condition: service_healthy
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      target: dev
    volumes:
      - '.:/var/www/html'
    entrypoint: []
    command: [ "php", "bin/console", "messenger:consume", "async", "--time-limit=3600", "-vv" ]
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:18.4
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "app", "-U", "user" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/data/postgresql:/var/lib/postgresql:rw
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
