# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            Symfony\Component\Messenger\MessageBusInterface $commandBus: '@command.bus'
            Symfony\Component\Messenger\MessageBusInterface $queryBus: '@query.bus'
            Symfony\Component\Messenger\MessageBusInterface $eventBus: '@event.bus'

    App\:
        resource: '../src/'
