name: Code Quality

on:
    push:

jobs:
    checks:
        name: Code checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.5'
                  extensions: bcmath, uuid, amqp, pdo_pgsql
                  coverage: xdebug
                  tools: composer

            - name: Cache Composer dependencies
              uses: actions/cache@v5
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}
                  restore-keys: composer-

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-progress

            - name: Coding Standards
              run: composer lint:check

            - name: Static Analysis
              run: composer stan

            - name: Unit and Feature Tests
              run: composer test

            - name: Mutation Tests
              run: composer mutation
